name: Publish Docker Container Registry
#on: [push]
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: marlluslustosa/dockertest
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
        registry: https://ghcr.io

